# .github/api/createCommitOnBranch.gql
mutation (
  $githubRepository: String!,
  $branchName: String!,
  $expectedHeadOid: GitObjectID!,
  $messageHeadline: String!,
  $messageBody: String,
  $additions: [FileAddition!],
  $deletions: [FileDeletion!]
) {
  createCommitOnBranch(input: {
    branch: {
      repositoryNameWithOwner: $githubRepository,
      branchName: $branchName
    },
    message: {
      headline: $messageHeadline,
      body: $messageBody
    },
    fileChanges: {
      additions: $additions,
      deletions: $deletions
    },
    expectedHeadOid: $expectedHeadOid
  }) {
    commit { oid, url }
  }
}
