# .github/api/createCommitOnBranch.gql
mutation (
    $githubRepository: String!,
    $branchName: String!,
    $expectedHeadOid: GitObjectID!,
    $messageHeadline: String!,
    $messageBody: String,
    $files: [FileAddition!]!,
    $deletions: [FileDeletion!]!
) {
  createCommitOnBranch(input: {
    branch: {
      repositoryNameWithOwner: $githubRepository,
      branchName: $branchName
    },
    message: {
      headline: $messageHeadline,
      body: $messageBody
    },
    fileChanges: {
      additions: $files,
      deletions: $deletions
    },
    expectedHeadOid: $expectedHeadOid
  }) {
    commit { url }
  }
}
